### PR TITLE
DA-4560: Dockerize the git connector

### PR DESCRIPTION
**Pull request by linonymous**
- add dockerfile

Signed-off-by: linonymous <linonymous@gmail.com>

### CODE REVIEW

**Comment by linonymous** [comment]
This is a bit unsecure approach as we need to add up the private key to fetch private packages to build the code inside container. Other possible way is to directly add up the binary file into the container & use the same.

**Review by lukaszgryglicki — COMMENTED** [review]
I would go with the binary, also this repo is public, so I don't know what needs to be private in Dockerfile? Why not just build `git`, `gitops` and copy `detect_removed_commits.sh` into the smallest possible base image, like Alpine linux?

**Comment by linonymous** [comment]
> I would go with the binary, also this repo is public, so I don't know what needs to be private in Dockerfile? Why not just build `git`, `gitops` and copy `detect_removed_commits.sh` into the smallest possible base image, like Alpine linux?

@lukaszgryglicki this repo is dependent upon `lfx-events-schema` which is a private repo & cant be built with go mod without github auth. So is the case. Building binary seems simple approach & would be a pretty light weight container.

**Comment by lukaszgryglicki** [comment]
So I would build on top of alpine linux - putting only required binaries and nothing more.

**Comment by linonymous** [comment]
> So I would build on top of alpine linux - putting only required binaries and nothing more.

yes, added it up.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm
This is exactly what i was thinking about, thanks!

**Pull request merged**
